
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: my-org-agent-pool
  
jobs:
# - job: seconde_job
#   steps:
#   - task: Bash@3
#     inputs:
#       targetType: 'inline'
#       script: |
#         # Write your commands here
#         touch /home/moi/pipeline-created-file
#         echo 'Hello world' > /home/moi/pipeline-created-file
- job: read_secrets_from_vault
  steps:
  - task: VaultReadKV@4
    inputs:
      strUrl: 'http://18.134.158.197:8200'
      ignoreCertificateChecks: true
      useProxy: 'none'
      strNamespaces: '/'
      strAuthType: 'userpass'
      strUsername: 'admin'
      strPassword: 'admin'
      strKVEnginePath: 'kv'
      kvVersion: 'v2'
      strSecretPath: 'app1'
      strPrefixType: 'custom'
      strVariablePrefix: 'AZ'
      replaceCR: true
      strCRPrefix: '_'

- job: write_vault_secrets
  dependsOn: read_secrets_from_vault
  steps:
  - script: |
      touch /home/moi/vault-secrets
  - task: PythonScript@0
    inputs:
      scriptSource: 'inline'
      script: |
        from environs import Env
        env = Env()
        env.read_env()
        with open("/home/moi/vault-secrets", "a") as f:
            with env.prefixed("AZ_"):
                f.write("env 1 is: " + env('TEST') + ' ')
      pythonInterpreter: '/usr/bin/python3'