name: Evnets Workflow
on:
    push:
        branches: 
            - main
    pull_request:
    workflow_dispatch:
jobs:
    test-events:
        name: test envents to trigger the workflow
        runs-on: ubuntu-latest
        steps:
            - run: | 
                echo hello world
            - run: |
                print('hello world')
              shell: python

