name: learning actions for mlops
on: [push]

jobs:
  update_ubuntu:
    name: First Job 
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update
          echo "hello world"
  install-wandb:
    name: install wandb package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          pip install -r requirments.txt
          python3 test.py
  read-secret:
    name: Read Repo Secret 
    runs-on: ubuntu-latest
    steps:
      - run: |
          env | grep -i 'my_env'
        env:
          MY_ENV: "${{ secrets.HELLO_SECRET }}"
  use-python-shell:
    name: Use run to run python code
    runs-on: ubuntu-latest
    steps:
      - run: |
          import os
          print(len(os.getenv('MY_ENV')))
        shell: python
        env:
          MY_ENV: "${{ secrets.HELLO_SECRET }}"
                